GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzAxMjMxNDgzLCJleHAiOjE3MDEyMzE0OTh9.u4pj6LHWiXX94vUnttcGuiOdg39CboEP3yrgc66I5ng

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzAxMjMyNjE4fQ.laSwG9JasqnHeqPmn3abKNJT6AVfQAqc5go7iyZYMzg"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzAxMjMyNjE4fQ.laSwG9JasqnHeqPmn3abKNJT6AVfQAqc5go7iyZYMzg"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Jim"
}